# Generated by Django 2.2.16 on 2023-03-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20230327_1344'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_cannot_follow_self',
        ),
    ]
